loctube/__init__.py
# -*- coding: utf-8 -*-

from app import create_app

loctube/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin
from .models import Video

loctube/admin/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required

from ..extensions import db
from ..decorators import admin_required

from ..user import User
from loctube.admin.forms import UserForm, CrawlerForm, VideoForm
from loctube.admin.models import Video
import requests
import json
from flask import jsonify
from flask_wtf import csrf
from geoalchemy.base import WKTSpatialElement, WKBSpatialElement

from geoalchemy import (GeometryColumn, Point, Polygon, LineString,GeometryDDL, WKTSpatialElement, 
                        DBSpatialElement, GeometryExtensionColumn,WKBSpatialElement)
from geoalchemy.functions import functions
from nose.tools import ok_, eq_, raises, assert_almost_equal
from sqlalchemy import and_
  
from geoalchemy.mysql import MySQLComparator, mysql_functions
import random
import re
import sys
from random import randrange

admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/')
@login_required
@admin_required
def index():
    users = User.query.all()
    return render_template('admin/index.html', users=users, active='index')


@admin.route('/users')
@login_required
@admin_required
def users():
    users = User.query.all()
    return render_template('admin/users.html', users=users, active='users')


@admin.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        flash('User updated.', 'success')
         
    return render_template('admin/user.html', user=user, form=form)


@admin.route('/videos')
@login_required
@admin_required
def videos():
  
    pagination = None
    page = int(request.args.get('page', 1))
    pagination = Video.query.paginate(page=page, per_page=50)
  
    return render_template('admin/videos.html', pagination=pagination, active='videos')


@admin.route('/video/<int:video_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def video(video_id):
    video = Video.query.filter_by(id=video_id).first_or_404()
    form = VideoForm(obj=video, next=request.args.get('next'))

    if form.is_submitted():
        form.populate_obj(video)

        db.session.add(video)
        db.session.commit()

        flash('Video updated.', 'success')

    return render_template('admin/video.html', video=video, form=form)


@admin.route('/delete_video/<int:video_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_video(video_id):
    video = Video.query.filter_by(id=video_id).first_or_404()

    db.session.delete(video)
    db.session.commit()

    message = "Video ID="+ str(video_id) + " has been deleted"
    flash( message, 'success')

    return redirect(url_for('admin.videos'))


@admin.route('/crawler', methods=['GET', 'POST'])
@login_required
@admin_required
def crawler():
    form = CrawlerForm()
    error = None
    if request.method == 'GET':
        return render_template( "admin/crawler.html", form=form)

    
    if request.method == 'POST':

        loc_info_list = form.location_list.data.split('\r\n')
        
        message1 = ""
        message2 = ""
        for loc_info in loc_info_list:

            try: 
                if regex_compare("[0-9]+,[\w]+,[-0-9.]+,[-0-9.]+", loc_info) == False: continue

                location = loc_info.split(',')
               

                googlemap_url = "https://maps.googleapis.com/maps/api/geocode/json?address=" + location[2] + "," + location[3]

                googlemap_json = requests.get(googlemap_url) 
                # Convert it to a Python dictionary
                googlemap_data = json.loads(googlemap_json.text)

                if 'ZERO_RESULTS' in str(googlemap_data['status']): continue
          
                googlemap_country = googlemap_data['results'][0]['address_components'][-1]['long_name'] + " " + googlemap_data['results'][0]['address_components'][-2]['long_name']
            
                #since last 2 element can be country name or zip code  get both and reject numbers via regEx
                country_regex = regex_find(r'[a-zA-Z]+', googlemap_country)

                youtube_url = "http://gdata.youtube.com/feeds/api/videos?alt=json&max-results=50" + "&q=" + location[1] +" " + country_regex
        
                # Get the youtube json
                youtube_json = requests.get(youtube_url)

                # Convert it to a Python dictionary
                youtube_data = json.loads(youtube_json.text)

                res = youtube_data['feed']['openSearch$totalResults']['$t']

                if int(res) != 0: 

                    tot_entry=0
                    for item in youtube_data['feed']['entry']:

                        title = (item['title']['$t'])

                        if location[1].strip().lower() in title.lower(): 

                            video = Video()

                            video.title = unicode(item['title']['$t'])

                            video.description = unicode(item['media$group']['media$description']['$t'])

                            video.video_url   = (item['link'][0]['href'].encode('utf-8'))

                            video.image_url1  = (item['media$group']['media$thumbnail'][0]['url'].encode('utf-8'))
                            video.image_url2  = (item['media$group']['media$thumbnail'][1]['url'].encode('utf-8'))


                            video.location_lat = location[2]
                            video.location_lng = location[3]
                            video.location_link = location[4]

                            wkt_spot = "POINT(" + location[2] + " " + location[3] +")"
                            video.location_lat_lng = WKTSpatialElement(wkt_spot)

                            db.session.add(video)

                            db.session.commit()
                            tot_entry=tot_entry+1

                    message1 = message1+ location[0] + "-"+ str(tot_entry) +" "

            except Exception as inst:
                message2 += str(inst) + " - "
                pass


        flash(message1 + ' has been crawled [Id-NumberofIndexed] ' + " .... " + message2 , 'has been crawled')

        return render_template( "admin/crawler.html",form=form, active='crawler')


@admin.route('/video_search', methods=['GET', 'POST'])
def video_search():


    # this method is temporary  since geoalchemy  has problem with sqlite  video can not be found by distance between to coordinates. 
    if request.method == 'POST':


        #db.session.query(Video).filter()

        #test3 = db.session.scalar(functions._within_distance(Video.location_lat_lng, 'POINT(-88.9139332929936 35.5082802993631)', 10))
        
        posted_corr = 'POINT(' + request.data.replace('"','').replace(',',' ') + ')'

        geo_data_list = db.session.query(Video.video_url).filter(functions._within_distance(Video.location_lat_lng, posted_corr, 0.6))[:30]

        #test2 = session.scalar(functions._within_distance('POINT(-88.9139332929936 42.5082802993631)', 'POINT(-88.9139332929936 35.5082802993631)', 10)) 

        geo_data_dict ={}
        for i in range(len(geo_data_list)):
            geo_data_dict[i] = geo_data_list[i][0]




        #youtube_link = "http://gdata.youtube.com/feeds/api/videos?v=2&alt=json&prettyprint=true&location=" + request.data.replace('"','') + "!&location-radius=6mi&max-results=12";
    
        #youtube_request = requests.get(youtube_link)

        ## Convert it to a Python dictionary
        #youtube_data = json.loads(youtube_request.text)

        #test = request.data

        #coor = request.data.split(',')


        return jsonify(geo_data_dict)

def find_by_geo(event):
    radius = 20000

    #geog = WKTElement('POINT({} {})'.format(lng, lat))

    distance_query = Video.location_lat_lng.ST_Distance(event.geog).label('distance')
    nearby_query = Video.location_lat_lng.ST_DWithin(event.geog,radius)

    city_query = db.session.query(Video, distance_query)

    city_query = city_query.filter(nearby_query)

    videos = city_query.all()

    return videos




def regex_find(pat,text):
     match = re.search(pat,text)
     if match: 
        return match.group()
     else: 
         return None


def regex_compare(pat,text):

     text = text.replace(" ", "")
     match = re.search(pat,text)
     if match: 
        return True
     else: 
        return False

loctube/api/__init__.py
# -*- coding: utf-8 -*-

from .views import api

loctube/api/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, current_app, request, jsonify
from flask.ext.login import login_user, current_user, logout_user

from ..user import User


api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/login', methods=['POST'])
def login():
    if current_user.is_authenticated():
        return jsonify(flag='success')

    username = request.form.get('username')
    password = request.form.get('password')
    if username and password:
        user, authenticated = User.authenticate(username, password)
        if user and authenticated:
            if login_user(user, remember='y'):
                return jsonify(flag='success')

    current_app.logger.debug('login(api) failed, username: %s.' % username)
    return jsonify(flag='fail', msg='Sorry, try again.')


@api.route('/logout')
def logout():
    if current_user.is_authenticated():
        logout_user()
    return jsonify(flag='success', msg='Logouted.')

loctube/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

loctube/frontend/views.py
# -*- coding: utf-8 -*-

from uuid import uuid4

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort)
from flask.ext.mail import Message
from flask.ext.babel import gettext as _
from flask.ext.login import login_required, login_user, current_user, logout_user, confirm_login, login_fresh

from ..user import User, UserDetail
from ..extensions import db, mail, login_manager, oid
from .forms import SignupForm, LoginForm, RecoverPasswordForm, ReauthForm, ChangePasswordForm, OpenIDForm, CreateProfileForm


frontend = Blueprint('frontend', __name__)


@frontend.route('/login/openid', methods=['GET', 'POST'])
@oid.loginhandler
def login_openid():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = OpenIDForm()
    if form.validate_on_submit():
        openid = form.openid.data
        current_app.logger.debug('login with openid(%s)...' % openid)
        return oid.try_login(openid, ask_for=['email', 'nickname'], ask_for_optional=['fullname'])
    return render_template('frontend/login_openid.html', form=form, error=oid.fetch_error())


@oid.after_login
def create_or_login(resp):
    user = User.query.filter_by(openid=resp.identity_url).first()
    if user and login_user(user):
        flash('Logged in', 'success')
        return redirect(oid.get_next_url() or url_for('user.index'))
    return redirect(url_for('frontend.create_profile', next=oid.get_next_url(),
            name=resp.fullname or resp.nickname, email=resp.email,
            openid=resp.identity_url))


@frontend.route('/create_profile', methods=['GET', 'POST'])
def create_profile():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = CreateProfileForm(name=request.args.get('name'),
            email=request.args.get('email'),
            openid=request.args.get('openid'))

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()

        if login_user(user):
            return redirect(url_for('user.index'))

    return render_template('frontend/create_profile.html', form=form)


@frontend.route('/')
def index():
    current_app.logger.debug('debug')

    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    page = int(request.args.get('page', 1))
    pagination = User.query.paginate(page=page, per_page=5)
    return render_template('index.html', pagination=pagination)


@frontend.route('/search')
def search():
    keywords = request.args.get('keywords', '').strip()
    pagination = None
    if keywords:
        page = int(request.args.get('page', 1))
        pagination = User.search(keywords).paginate(page, 5)
    else:
        flash(_('Please input keyword(s)'), 'error')
    return render_template('frontend/search.html', pagination=pagination, keywords=keywords)


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)

        if user and authenticated:
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):
                flash(_("Logged in"), 'success')
            return redirect(form.next.data or url_for('user.index'))
        else:
            flash(_('Sorry, invalid login'), 'error')

    return render_template('frontend/login.html', form=form)


@frontend.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(_('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(_('Password is wrong.'), 'error')
    return render_template('frontend/reauth.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


@frontend.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = SignupForm(next=request.args.get('next'))

    if form.validate_on_submit():
        user = User()
        user.user_detail = UserDetail()
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        if login_user(user):
            return redirect(form.next.data or url_for('user.index'))

    return render_template('frontend/signup.html', form=form)


@frontend.route('/change_password', methods=['GET', 'POST'])
def change_password():
    user = None
    if current_user.is_authenticated():
        if not login_fresh():
            return login_manager.needs_refresh()
        user = current_user
    elif 'activation_key' in request.values and 'email' in request.values:
        activation_key = request.values['activation_key']
        email = request.values['email']
        user = User.query.filter_by(activation_key=activation_key) \
                         .filter_by(email=email).first()

    if user is None:
        abort(403)

    form = ChangePasswordForm(activation_key=user.activation_key)

    if form.validate_on_submit():
        user.password = form.password.data
        user.activation_key = None
        db.session.add(user)
        db.session.commit()

        flash(_("Your password has been changed, please log in again"),
              "success")
        return redirect(url_for("frontend.login"))

    return render_template("frontend/change_password.html", form=form)


@frontend.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash('Please see your email for instructions on '
                  'how to access your account', 'success')

            user.activation_key = str(uuid4())
            db.session.add(user)
            db.session.commit()

            url = url_for('frontend.change_password', email=user.email, activation_key=user.activation_key, _external=True)
            html = render_template('macros/_reset_password.html', project=current_app.config['PROJECT'], username=user.name, url=url)
            message = Message(subject='Reset your password in ' + current_app.config['PROJECT'], html=html, recipients=[user.email])
            mail.send(message)

            return render_template('frontend/reset_password.html', form=form)
        else:
            flash(_('Sorry, no user found for that email address'), 'error')

    return render_template('frontend/reset_password.html', form=form)


@frontend.route('/help')
def help():
    return render_template('frontend/footers/help.html', active="help")

loctube/settings/__init__.py
# -*- coding: utf-8 -*-

from .views import settings

loctube/user/__init__.py
# -*- coding: utf-8 -*-

from .models import UserDetail, User
from .views import user
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

loctube/templates/layouts/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{{ page_title|default(_('Project')) }}{% endblock %} - Project</title>
    <meta name="description" content="loctube (Flask bone) is a Flask (Python microframework) template/bootstrap/boilerplate application.">
    <meta name="author" content="Wilson Xu">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script type='text/javascript' src='http://code.jquery.com/jquery-1.8.3.js'></script>

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&language=en"></script>
    <script src="{{ url_for('static', filename='js/vendor/jquery.fancybox.js') }}"></script>

    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.fancybox.css') }}">
    {% endblock %}

    {% block css_style %}
    {% endblock %}

    {% block js_top %}
    <script src="//upcdn.b0.upaiyun.com/libs/modernizr/modernizr-2.6.2.min.js"></script>


    {% endblock %}



    <style type='text/css'>
        .fancybox-nav {
            width: 60px;
        }

        .fancybox-nav span {
            visibility: visible;
        }

        .fancybox-next {
            right: -60px;
        }

        .fancybox-prev {
            left: -60px;
        }
    </style>



    <script type='text/javascript'>
//<![CDATA[

        // Fires whenever a player has finished loading
        function onPlayerReady(event) {
            event.target.playVideo();
        }

        // Fires when the player's state changes.
        function onPlayerStateChange(event) {
            // Go to the next video after the current one is finished playing
            if (event.data === 0) {
                $.fancybox.next();
            }
        }

        // The API will call this function when the page has finished downloading the JavaScript for the player API
        function onYouTubePlayerAPIReady() {

            // Initialise the fancyBox after the DOM is loaded
            $(document).ready(function () {
                $(".fancybox")
                    .attr('rel', 'gallery')
                    .fancybox({
                        openEffect: 'none',
                        closeEffect: 'none',
                        nextEffect: 'none',
                        prevEffect: 'none',
                        padding: 0,
                        margin: 50,
                        beforeShow: function () {
                            // Find the iframe ID
                            var id = $.fancybox.inner.find('iframe').attr('id');

                            // Create video player object and add event listeners
                            var player = new YT.Player(id, {
                                events: {
                                    'onReady': onPlayerReady,
                                    'onStateChange': onPlayerStateChange
                                }
                            });
                        }
                    });
            });

        }
        //]]>

    </script>


</head>
<body>
    {% include "macros/_ask_user_to_update_ie.html" %}

        {% block topbar %}
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class='brand' href='{{ url_for('frontend.index') }}'>LocTube</a>

                    {% if current_user.is_authenticated() %}
                    <form class="navbar-search pull-left" action="{{ url_for('frontend.search') }}">
                        <input type='text' class="search-query" name='keywords' value='{{ keywords|default('') }}' placeholder='Search' />
                    </form>
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav">
                            {% if current_user.is_admin() %}
                            <li><a href="{{ url_for('admin.index') }}">{{ current_user.name }}</a></li>
                            {% else %}
                            <li><a href="{{ url_for('user.index') }}">{{ current_user.name }}</a></li>
                            {% endif %}
                            <li><a href="{{ url_for('settings.profile') }}">Settings</a></li>
                            <li><a href="{{ url_for('frontend.logout') }}">Log out</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav">
                            <li><span><a class="btn btn-success" href="{{ url_for('frontend.signup') }}"><strong>Sign up</strong></a></span></li>
                            <li><a href="{{ url_for('frontend.login') }}">Sign in</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endblock %}

        {% block flash_message %}
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                <div class="container">
                    <div id='flash_message_container'>
                        {% for category, msg in messages %}
                            <div class="alert alert-{{ category }}">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                {{ msg }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            {% endwith %}
        {% endblock %}

        {% block container %}
        <div class="container">

            {% block top %}
                {% if tabs %}
                <div>
                    <ul class="nav nav-tabs">
                        {% for tab, link in tabs %}
                        <li class="{% if active == tab %}active{% endif %}">
                            <a href="{{ link }}">{{ tab|capitalize }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            {% endblock %}

            {% block body %}
            {% endblock %}

        </div>
        {% endblock %}
        <div id="push"></div>

    <footer id="footer">
        <ul class="footer-links">
            <li>2014</li>
            <li><a href='https://github.com/vergili/loctube'>About</a></li>
            <li class="muted">&middot;</li>
            <li><a href='{{ url_for('frontend.help') }}'>Help</a></li>
            <li class="muted">&middot;</li>
            <li><a href=''>Terms</a></li>
            <li class="muted">&middot;</li>
            <li><a href=''>Blog</a></li>
        </ul>
    </footer>

    {% block js_btm %}
    <!--
    {% set jquery_path = url_for('static', filename='js/vendor/jquery-1.8.3.min.js') %}
    <script>window.jQuery || document.write('<script src="{{ jquery_path }}"><\/script>')</script>
    -->
    <script src="{{ url_for('static', filename='js/plugins.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/bootstrap.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% endblock %}

    {% block ga %}
    {% include "macros/_google_analytics.html" %}
    {% endblock %}
</body>
</html>

loctube/templates/layouts/base_bootstrap3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Fixed Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/navbar-fixed-top/navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        .footer {
            position: relative;
            bottom: 0;
            width: 100%;
            /* Set the fixed height of the footer here */
            height: 100px;
            background-color: #f5f5f5;
        }
        body {
            min-height: 100%;
            padding-top: 70px;
        }
    </style>
</head>

<body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../navbar/">Default</a></li>
                    <li><a href="../navbar-static-top/">Static top</a></li>
                    <li class="active"><a href="./">Fixed top</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>


    {% block flash_message %}
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    <div class="container">
        <div id='flash_message_container'>
            {% for category, msg in messages %}
            <div class="alert alert-{{ category }}">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ msg }}
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    {% endwith %}
    {% endblock %}

    {% block container %}
    <div class="container">
        {% block top %}
        {% if tabs %}
        <div>
            <ul class="nav nav-tabs">
                {% for tab, link in tabs %}
                <li class="{% if active == tab %}active{% endif %}">
                    <a href="{{ link }}">{{ tab|capitalize }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endblock %}

        {% block body %}
        {% endblock %}

    </div>
    {% endblock %}
    <div id="push"></div>



    <div class="footer">
        <div class="container">
            <p class="text-muted">Place sticky footer content here.</p>
        </div>
    </div>

    <!-- /container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
</body>
</html>